name: pharma_go
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  google_maps_flutter: ^2.2.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1 # Pour la police Poppins
  http: ^1.4.0 # Pour charger les images depuis le web
  cached_network_image: ^3.2.3
  camera: ^0.11.1  # Pour l'accès à la caméra
  image_picker: ^1.0.2  # Pour sélectionner/capturer des images
  mobile_scanner: ^7.0.0  # Pour scanner les codes-barres/QR
  provider: ^6.1.5  # Pour la gestion d'état
  intl : ^0.18.1  # Pour la localisation et le formatage des dates
  # http: ^0.13.5  # Pour les requêtes API (recherche)

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
