// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHszq2GXnVNx3VC2_cfRqAF28WJIY-X8',
    appId: '1:762589326246:web:6469a781885a6dbe25bd67',
    messagingSenderId: '762589326246',
    projectId: 'pharmago-1b4ff',
    authDomain: 'pharmago-1b4ff.firebaseapp.com',
    storageBucket: 'pharmago-1b4ff.firebasestorage.app',
    measurementId: 'G-L1B39WL2B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJg6rA9SZUeTTAPnda7ctk2lwQabrid0',
    appId: '1:762589326246:android:251f3b2147e2a26625bd67',
    messagingSenderId: '762589326246',
    projectId: 'pharmago-1b4ff',
    storageBucket: 'pharmago-1b4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sTATXDQ7EgZlWFql4lZh6ajJezSbmEE',
    appId: '1:762589326246:ios:2db717dc1736c9c125bd67',
    messagingSenderId: '762589326246',
    projectId: 'pharmago-1b4ff',
    storageBucket: 'pharmago-1b4ff.firebasestorage.app',
    iosBundleId: 'com.example.pharmaGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4sTATXDQ7EgZlWFql4lZh6ajJezSbmEE',
    appId: '1:762589326246:ios:2db717dc1736c9c125bd67',
    messagingSenderId: '762589326246',
    projectId: 'pharmago-1b4ff',
    storageBucket: 'pharmago-1b4ff.firebasestorage.app',
    iosBundleId: 'com.example.pharmaGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFHszq2GXnVNx3VC2_cfRqAF28WJIY-X8',
    appId: '1:762589326246:web:f76e4ca2b17efd6925bd67',
    messagingSenderId: '762589326246',
    projectId: 'pharmago-1b4ff',
    authDomain: 'pharmago-1b4ff.firebaseapp.com',
    storageBucket: 'pharmago-1b4ff.firebasestorage.app',
    measurementId: 'G-GS5HJNDSR3',
  );
}
